package metric.execution;

public enum Metric {
    GIT_AVERAGE_COMMIT_SIZE,
    GIT_AVERAGE_FILE_SIZE,
    GIT_COMMIT_COUNT,
    GIT_COMMITS_ON_MASTER,
    GIT_CONTRIBUTOR_ENTROPY,
    GIT_LINES_OF_CODE,
    GIT_NUMBER_OF_BRANCHES,
    GIT_NUMBER_OF_CONTRIBUTORS,
    GIT_NUMBER_OF_FILES,
    GIT_NUMBER_OF_REFACTORING_COMMITS,
    GIT_PROJECT_DURATION,
    ALLEN_GRAPH_SIZE,
    ALLEN_COMPLEXITY,
    ALLEN_COHESION,
    ALLEN_COUPLING
}
